/**
 * Algorithm-pattern catalog (server-side source of truth).
 *
 * Data comes from src/data/pattern-catalog.json, generated by
 * roadmap-tools/build-catalog.mjs — the SAME file the batch classifier reads, so
 * the app and the backfill never drift. Import only the TYPES into client code
 * (`import type { ... }`) so the JSON stays out of the client bundle.
 */
import catalog from "@/data/pattern-catalog.json";

export type PatternPriority = "Critical" | "High" | "Medium" | "Low";

export interface Pattern {
  name: string;
  slug: string;
  category: string;
  categorySlug: string;
  priority: PatternPriority;
  description: string;
  whenToUse: string;
  recognition: string[];
  mistakes: string[];
  time: string;
  space: string;
  importance: string;
}

export interface PatternCategoryDef {
  category: string;
  categorySlug: string;
  priority: PatternPriority;
  patternSlugs: string[];
}

const data = catalog as unknown as {
  categories: PatternCategoryDef[];
  patterns: Pattern[];
  tagMap: Record<string, string[]>;
  topicMap: Record<string, string[]>;
};

export const ALL_PATTERNS: Pattern[] = data.patterns;
export const PATTERN_CATEGORIES: PatternCategoryDef[] = data.categories;
export const PATTERN_BY_SLUG = new Map(data.patterns.map((p) => [p.slug, p]));
export const getPattern = (slug: string): Pattern | undefined => PATTERN_BY_SLUG.get(slug);

// ---- runtime classifier (Step 14: classify on write / backfill single docs) ----
const PATTERN_FIELD_MAP: Record<string, string[]> = {
  "Sliding Window": ["variable-window"], "Two Pointer": ["two-pointer"], Greedy: ["greedy-choice"],
  DP: ["memoization", "tabulation"], Graph: ["graph-dfs", "graph-bfs"], DFS: ["graph-dfs"], BFS: ["graph-bfs"],
  Trie: ["trie"], "Binary Search": ["binary-search"], "Monotonic Stack": ["monotonic-stack"],
  Backtracking: ["subset", "permutation", "combination"], Heap: ["priority-queue-heap", "top-k"],
  Hashing: ["hashmap"], Tree: ["tree-traversal"], Recursion: ["recursion"], Bitmask: ["bitmask"],
  Math: ["gcd", "modular-arithmetic"],
};
const norm = (s: string) => s.toLowerCase().trim();

export interface ClassifyInput {
  tags?: string[];
  topic?: string;
  pattern?: string;
}

/** Deterministic multi-pattern classification from official tags + topic + pattern. */
export function classifyQuestion(q: ClassifyInput): {
  patterns: string[];
  confidence: number;
  method: string;
} {
  const valid = PATTERN_BY_SLUG;
  const fromTags = new Set<string>();
  for (const t of q.tags || []) for (const s of data.tagMap[norm(t)] || []) if (valid.has(s)) fromTags.add(s);
  const fromField = new Set<string>();
  for (const s of PATTERN_FIELD_MAP[q.pattern || ""] || []) if (valid.has(s)) fromField.add(s);

  const all = new Set<string>([...fromTags, ...fromField]);
  let method: string, confidence: number;
  if (fromTags.size) { method = "tags"; confidence = fromTags.size >= 3 ? 0.95 : 0.9; }
  else if (fromField.size) { method = "pattern-field"; confidence = 0.75; }
  else { method = "topic"; confidence = 0.5; }

  if (!all.size) {
    for (const s of data.topicMap[q.topic || ""] || []) if (valid.has(s)) all.add(s);
    method = "topic"; confidence = 0.5;
  }
  if (!all.size) { all.add("ad-hoc"); method = "fallback"; confidence = 0.35; }
  return { patterns: [...all].slice(0, 8), confidence, method };
}

// ---- API payload shapes ----
export interface PatternStat {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  priority: PatternPriority;
  total: number;
  solved: number;
  remaining: number;
  completionPct: number;
  easy: number;
  medium: number;
  hard: number;
  leetcode: number;
  codeforces: number;
  striver: number;
}

export interface PatternDashboard {
  generatedAt: string;
  totalPatterns: number;
  totalAssignments: number;
  summary: { totalQuestions: number; classified: number; avgPatternsPerQuestion: number };
  categories: {
    category: string;
    categorySlug: string;
    priority: PatternPriority;
    total: number;
    patterns: PatternStat[];
  }[];
  mostUsed: PatternStat[];
  leastUsed: PatternStat[];
}

export interface PatternQuestion {
  id: string;
  title: string;
  platform: string;
  difficulty: string;
  topic: string;
  problemLink: string;
  status: string;
  favorite: boolean;
  patterns: string[];
}

export interface PatternDetail extends PatternStat {
  description: string;
  whenToUse: string;
  recognition: string[];
  mistakes: string[];
  time: string;
  space: string;
  importance: string;
  relatedPatterns: { slug: string; name: string }[];
  questions: {
    items: PatternQuestion[];
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}
