/**
 * Curated sample questions used by the `/api/seed` endpoint. Each entry is a
 * partial record; the server fills defaults through the Zod schema. This gives
 * a freshly-installed instance a realistic, populated dashboard.
 */
export const SAMPLE_QUESTIONS: Record<string, unknown>[] = [
  {
    title: "Two Sum",
    problemLink: "https://leetcode.com/problems/two-sum/",
    platform: "LeetCode",
    difficulty: "Easy",
    topic: "Arrays",
    subtopic: "Basic Arrays",
    pattern: "Hashing",
    companies: ["Amazon", "Google", "Apple"],
    concept: "Use a hash map to store complements while scanning once.",
    approach: "Iterate, check if target - nums[i] seen; else store nums[i] -> i.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    status: "Solved",
    favorite: true,
    rating: 5,
    attemptCount: 1,
    interviewLevel: "Warmup",
    estimatedTime: 15,
    tags: ["hashmap", "classic"],
  },
  {
    title: "Best Time to Buy and Sell Stock",
    problemLink: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    platform: "LeetCode",
    difficulty: "Easy",
    topic: "Arrays",
    subtopic: "Kadane",
    pattern: "DP",
    companies: ["Amazon", "Microsoft"],
    concept: "Track minimum price and best profit so far.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    status: "Solved",
    rating: 4,
    attemptCount: 2,
    estimatedTime: 20,
    tags: ["greedy"],
  },
  {
    title: "Maximum Subarray",
    problemLink: "https://leetcode.com/problems/maximum-subarray/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Arrays",
    subtopic: "Kadane",
    pattern: "DP",
    companies: ["Amazon", "LinkedIn", "Microsoft"],
    concept: "Kadane's algorithm — running max ending here.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    status: "Solved",
    favorite: true,
    rating: 5,
    estimatedTime: 20,
    tags: ["kadane"],
  },
  {
    title: "Longest Substring Without Repeating Characters",
    problemLink: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Strings",
    subtopic: "String Manipulation",
    pattern: "Sliding Window",
    companies: ["Amazon", "Adobe", "Bloomberg"],
    concept: "Sliding window with last-seen index map.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(min(n,charset))",
    status: "Need Revision",
    revisionNeeded: true,
    rating: 4,
    attemptCount: 3,
    estimatedTime: 30,
    tags: ["sliding-window"],
  },
  {
    title: "Trapping Rain Water",
    problemLink: "https://leetcode.com/problems/trapping-rain-water/",
    platform: "LeetCode",
    difficulty: "Hard",
    topic: "Arrays",
    subtopic: "Two Pointers",
    pattern: "Two Pointer",
    companies: ["Amazon", "Google", "Goldman Sachs"],
    concept: "Two pointers tracking left/right max.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    status: "Attempted",
    rating: 5,
    attemptCount: 2,
    interviewLevel: "Onsite",
    estimatedTime: 45,
    tags: ["hard", "two-pointer"],
  },
  {
    title: "Valid Parentheses",
    problemLink: "https://leetcode.com/problems/valid-parentheses/",
    platform: "LeetCode",
    difficulty: "Easy",
    topic: "Stack",
    subtopic: "Basic Stack",
    pattern: "Monotonic Stack",
    companies: ["Amazon", "Microsoft", "Meta"],
    concept: "Push opens, match closes with stack top.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    status: "Solved",
    rating: 3,
    estimatedTime: 15,
    tags: ["stack"],
  },
  {
    title: "Largest Rectangle in Histogram",
    problemLink: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    platform: "LeetCode",
    difficulty: "Hard",
    topic: "Stack",
    subtopic: "Monotonic Stack",
    pattern: "Monotonic Stack",
    companies: ["Google", "Amazon"],
    concept: "Monotonic increasing stack of indices.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    status: "Revisit",
    revisionNeeded: true,
    rating: 5,
    attemptCount: 4,
    interviewLevel: "Hard Onsite",
    estimatedTime: 50,
    tags: ["monotonic-stack"],
  },
  {
    title: "Reverse Linked List",
    problemLink: "https://leetcode.com/problems/reverse-linked-list/",
    platform: "LeetCode",
    difficulty: "Easy",
    topic: "Linked List",
    subtopic: "Reverse",
    pattern: "Recursion",
    companies: ["Amazon", "Microsoft", "Adobe"],
    concept: "Iterative pointer reversal or recursion.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    status: "Solved",
    favorite: true,
    rating: 4,
    estimatedTime: 15,
    tags: ["linkedlist"],
  },
  {
    title: "Linked List Cycle",
    problemLink: "https://leetcode.com/problems/linked-list-cycle/",
    platform: "LeetCode",
    difficulty: "Easy",
    topic: "Linked List",
    subtopic: "Fast Slow Pointer",
    pattern: "Two Pointer",
    companies: ["Amazon", "Oracle"],
    concept: "Floyd's tortoise and hare.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    status: "Solved",
    rating: 4,
    estimatedTime: 15,
    tags: ["floyd"],
  },
  {
    title: "Binary Tree Level Order Traversal",
    problemLink: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Trees",
    subtopic: "BFS",
    pattern: "BFS",
    companies: ["Amazon", "Microsoft", "Meta"],
    concept: "Queue-based breadth-first traversal.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    status: "Solved",
    rating: 4,
    estimatedTime: 25,
    tags: ["bfs", "tree"],
  },
  {
    title: "Lowest Common Ancestor of a Binary Tree",
    problemLink: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Trees",
    subtopic: "LCA",
    pattern: "Tree",
    companies: ["Meta", "Amazon", "LinkedIn"],
    concept: "Post-order recursion returning found nodes.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(h)",
    status: "Need Revision",
    revisionNeeded: true,
    rating: 5,
    attemptCount: 2,
    interviewLevel: "Onsite",
    estimatedTime: 30,
    tags: ["tree", "recursion"],
  },
  {
    title: "Number of Islands",
    problemLink: "https://leetcode.com/problems/number-of-islands/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Graph",
    subtopic: "DFS",
    pattern: "DFS",
    companies: ["Amazon", "Google", "Microsoft", "Uber"],
    concept: "Flood fill each unvisited land cell.",
    timeComplexity: "O(m*n)",
    spaceComplexity: "O(m*n)",
    status: "Solved",
    favorite: true,
    rating: 5,
    estimatedTime: 30,
    tags: ["grid", "dfs"],
  },
  {
    title: "Course Schedule",
    problemLink: "https://leetcode.com/problems/course-schedule/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Graph",
    subtopic: "Topological Sort",
    pattern: "Graph",
    companies: ["Amazon", "Google", "DE Shaw"],
    concept: "Detect cycle via Kahn's algorithm / indegree.",
    timeComplexity: "O(V+E)",
    spaceComplexity: "O(V+E)",
    status: "Attempted",
    rating: 4,
    attemptCount: 1,
    estimatedTime: 35,
    tags: ["toposort"],
  },
  {
    title: "Network Delay Time",
    problemLink: "https://leetcode.com/problems/network-delay-time/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Graph",
    subtopic: "Dijkstra",
    pattern: "Graph",
    companies: ["Google", "Amazon"],
    concept: "Single-source shortest path with a min-heap.",
    timeComplexity: "O(E log V)",
    spaceComplexity: "O(V+E)",
    status: "Not Started",
    rating: 0,
    estimatedTime: 40,
    tags: ["dijkstra", "heap"],
  },
  {
    title: "Coin Change",
    problemLink: "https://leetcode.com/problems/coin-change/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    subtopic: "Tabulation",
    pattern: "DP",
    companies: ["Amazon", "Adobe", "Uber"],
    concept: "Unbounded knapsack minimizing coins.",
    timeComplexity: "O(amount*coins)",
    spaceComplexity: "O(amount)",
    status: "Need Revision",
    revisionNeeded: true,
    favorite: true,
    rating: 5,
    attemptCount: 3,
    interviewLevel: "Onsite",
    estimatedTime: 35,
    tags: ["dp", "knapsack"],
  },
  {
    title: "Longest Common Subsequence",
    problemLink: "https://leetcode.com/problems/longest-common-subsequence/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Dynamic Programming",
    subtopic: "LCS",
    pattern: "DP",
    companies: ["Amazon", "Google"],
    concept: "2D DP over prefixes of both strings.",
    timeComplexity: "O(n*m)",
    spaceComplexity: "O(n*m)",
    status: "Solved",
    rating: 4,
    estimatedTime: 30,
    tags: ["dp", "lcs"],
  },
  {
    title: "Edit Distance",
    problemLink: "https://leetcode.com/problems/edit-distance/",
    platform: "LeetCode",
    difficulty: "Hard",
    topic: "Dynamic Programming",
    subtopic: "Interval DP",
    pattern: "DP",
    companies: ["Google", "Amazon", "Nvidia"],
    concept: "Levenshtein DP: insert/delete/replace.",
    timeComplexity: "O(n*m)",
    spaceComplexity: "O(n*m)",
    status: "Revisit",
    revisionNeeded: true,
    rating: 5,
    attemptCount: 2,
    interviewLevel: "Hard Onsite",
    estimatedTime: 45,
    tags: ["dp"],
  },
  {
    title: "Median of Two Sorted Arrays",
    problemLink: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    platform: "LeetCode",
    difficulty: "Hard",
    topic: "Binary Search",
    subtopic: "Binary Search on Answer",
    pattern: "Binary Search",
    companies: ["Google", "Amazon", "Adobe", "Goldman Sachs"],
    concept: "Partition both arrays via binary search.",
    timeComplexity: "O(log(min(n,m)))",
    spaceComplexity: "O(1)",
    status: "Not Started",
    rating: 0,
    interviewLevel: "Hard Onsite",
    estimatedTime: 60,
    tags: ["binary-search", "hard"],
  },
  {
    title: "Search in Rotated Sorted Array",
    problemLink: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Binary Search",
    subtopic: "Rotated Arrays",
    pattern: "Binary Search",
    companies: ["Amazon", "Microsoft", "Uber", "Walmart"],
    concept: "Decide which half is sorted, then narrow.",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    status: "Solved",
    rating: 4,
    estimatedTime: 25,
    tags: ["binary-search"],
  },
  {
    title: "Word Search",
    problemLink: "https://leetcode.com/problems/word-search/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Recursion",
    subtopic: "Backtracking",
    pattern: "Backtracking",
    companies: ["Amazon", "Microsoft", "Bloomberg"],
    concept: "DFS backtracking over the grid.",
    timeComplexity: "O(m*n*4^L)",
    spaceComplexity: "O(L)",
    status: "Attempted",
    rating: 4,
    attemptCount: 1,
    estimatedTime: 40,
    tags: ["backtracking", "grid"],
  },
  {
    title: "N-Queens",
    problemLink: "https://leetcode.com/problems/n-queens/",
    platform: "LeetCode",
    difficulty: "Hard",
    topic: "Recursion",
    subtopic: "N Queens",
    pattern: "Backtracking",
    companies: ["Adobe", "Amazon"],
    concept: "Place queens row by row with conflict sets.",
    timeComplexity: "O(n!)",
    spaceComplexity: "O(n)",
    status: "Not Started",
    rating: 0,
    interviewLevel: "Onsite",
    estimatedTime: 50,
    tags: ["backtracking"],
  },
  {
    title: "Kth Largest Element in an Array",
    problemLink: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    platform: "LeetCode",
    difficulty: "Medium",
    topic: "Heap",
    subtopic: "Top K",
    pattern: "Heap",
    companies: ["Amazon", "Meta", "Sprinklr"],
    concept: "Min-heap of size k, or quickselect.",
    timeComplexity: "O(n log k)",
    spaceComplexity: "O(k)",
    status: "Solved",
    rating: 4,
    estimatedTime: 25,
    tags: ["heap", "quickselect"],
  },
  {
    title: "Single Number",
    problemLink: "https://leetcode.com/problems/single-number/",
    platform: "LeetCode",
    difficulty: "Easy",
    topic: "Bit Manipulation",
    subtopic: "XOR",
    pattern: "Bitmask",
    companies: ["Amazon", "Adobe"],
    concept: "XOR cancels pairs, leaving the unique value.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    status: "Solved",
    favorite: true,
    rating: 3,
    estimatedTime: 10,
    tags: ["xor"],
  },
  {
    title: "Sieve of Eratosthenes",
    problemLink: "https://cses.fi/problemset/task/1083",
    platform: "CSES",
    difficulty: "Easy",
    topic: "Mathematics",
    subtopic: "Sieve",
    pattern: "Math",
    companies: ["Directi", "Media.net"],
    concept: "Mark multiples of each prime.",
    timeComplexity: "O(n log log n)",
    spaceComplexity: "O(n)",
    status: "Solved",
    rating: 3,
    estimatedTime: 20,
    tags: ["primes", "math"],
  },
];
